"""Recent, official cases whose facts explicitly involve students or schools."""

from datetime import datetime


SOURCE_URL = "https://www.court.gov.cn/zixun/xiangqing/463111.html"


RECENT_STUDENT_CASES = (
    {
        "slug": "spc-2025-campus-management-01-stair-injury",
        "title": "赵小某诉某学校侵权责任纠纷案",
        "case_number": "最高法2025年涉校园管理民事纠纷典型案例一",
        "guiding_case_number": "",
        "court_name": "最高人民法院发布典型案例",
        "case_type": "民事",
        "cause": "教育机构责任纠纷",
        "legal_domain": "campus",
        "decision_date": None,
        "published_at": datetime(2025, 4, 23, 15, 6, 45),
        "summary": "12周岁学生放学下楼时自行摔倒受伤。学校长期开展安全教育、设置醒目提示，并在事发后及时通知家长、陪同就医。学生一方未能证明学校未尽教育管理职责。",
        "dispute_focus": "学生在校园内自行受伤，能否仅凭受伤地点在学校就要求学校承担侵权责任。",
        "judgment_result": "审理法院判决驳回学生要求学校赔偿医疗费、营养费和精神损失费等诉讼请求。",
        "judgment_reasoning": "事故并非设施缺陷导致；学校已进行常态化安全教育并设置提示，事后也及时救助，已履行必要的教育、管理职责。限制民事行为能力学生主张学校担责，应证明学校存在未尽职责的过错。",
        "ai_plain_language": "在学校受伤不等于学校必然赔偿。要看设施是否有隐患、老师是否尽到巡查和提醒义务、事发后是否及时救助，以及家长能否拿出学校存在管理过错的证据。",
        "keywords": "学生,校园受伤,教育机构责任,学校管理,举证责任",
        "source_external_id": "spc-463111-case-1",
        "source_url": SOURCE_URL,
        "categories": ("campus-rights",),
        "tags": ("学生事实明确", "校园受伤", "学校责任"),
        "laws": (("中华人民共和国民法典", "第一千二百条", "限制民事行为能力人在校受伤时教育机构的过错责任"),),
    },
    {
        "slug": "spc-2025-campus-management-02-student-push",
        "title": "王小某诉张小某、夏某、某小学健康权纠纷案",
        "case_number": "最高法2025年涉校园管理民事纠纷典型案例二",
        "guiding_case_number": "",
        "court_name": "最高人民法院发布典型案例",
        "case_type": "民事",
        "cause": "健康权纠纷",
        "legal_domain": "campus",
        "decision_date": None,
        "published_at": datetime(2025, 4, 23, 15, 6, 45),
        "summary": "两名7周岁学生在校内玩耍时，一方突然推拉导致另一方摔倒并损伤牙齿。学校事前有安全教育和值日巡查，事后及时送医、通知家长并组织协商。",
        "dispute_focus": "无民事行为能力学生在校被同学意外推倒，监护人与已履行教育管理职责的学校如何承担责任。",
        "judgment_result": "判令致害学生的监护人赔偿8000余元，认定学校已尽教育管理职责，不承担责任。",
        "judgment_reasoning": "致害学生的行为直接导致损害，应由其监护人承担相应侵权责任；学校有安全制度、教育和巡视安排，事件突发且事后处置及时，能够证明已尽到职责。",
        "ai_plain_language": "低龄学生在学校玩耍导致同学受伤时，通常先看致害学生监护人的责任；学校能否免责，要靠日常安全制度、值班记录和事后处置等证据证明。",
        "keywords": "学生,校园受伤,健康权,监护人责任,学校管理",
        "source_external_id": "spc-463111-case-2",
        "source_url": SOURCE_URL,
        "categories": ("campus-rights",),
        "tags": ("学生事实明确", "同学伤害", "监护责任"),
        "laws": (("中华人民共和国民法典", "第一千一百九十九条", "无民事行为能力人在教育机构受伤的责任规则"),),
    },
    {
        "slug": "spc-2025-campus-management-03-campus-violence",
        "title": "张小某诉蒋小某、某中学等健康权纠纷案",
        "case_number": "最高法2025年涉校园管理民事纠纷典型案例三",
        "guiding_case_number": "",
        "court_name": "最高人民法院发布典型案例",
        "case_type": "民事",
        "cause": "健康权纠纷",
        "legal_domain": "campus",
        "decision_date": None,
        "published_at": datetime(2025, 4, 23, 15, 6, 45),
        "summary": "八年级学生在课间持续殴打同学，并打伤上前劝阻的另一名学生，造成十级残疾。现场有多名学生围观，但学校未及时发现和制止。",
        "dispute_focus": "校园暴力直接致害人的监护人与未及时发现、制止冲突的学校应如何分担赔偿责任。",
        "judgment_result": "判决致害学生父母承担70%的赔偿责任，学校承担30%的赔偿责任。",
        "judgment_reasoning": "致害学生对损害具有主要过错，由其监护人承担主要责任；学校未针对课间活动进行必要管理，也未及时发现持续的殴打行为，教育管理存在不足。",
        "ai_plain_language": "遭遇校园暴力后，除了固定施暴经过、伤情和医疗票据，也应保存老师值班、学校报告和监控调取记录。学校未及时制止时，可能按过错承担相应责任。",
        "keywords": "学生,校园暴力,同学殴打,健康权,学校责任",
        "source_external_id": "spc-463111-case-3",
        "source_url": SOURCE_URL,
        "categories": ("campus-rights",),
        "tags": ("学生事实明确", "校园暴力", "学校责任"),
        "laws": (("中华人民共和国民法典", "第一千二百条", "限制民事行为能力人在教育机构受伤的责任规则"),),
    },
    {
        "slug": "spc-2025-campus-management-04-football-risk",
        "title": "林小某诉陈小某、某中学等健康权纠纷案",
        "case_number": "最高法2025年涉校园管理民事纠纷典型案例四",
        "guiding_case_number": "",
        "court_name": "最高人民法院发布典型案例",
        "case_type": "民事",
        "cause": "健康权纠纷",
        "legal_domain": "campus",
        "decision_date": None,
        "published_at": datetime(2025, 4, 23, 15, 6, 45),
        "summary": "两名有多年训练经验的高中生在午休期间自发踢球，一人在正常攻防接触中倒地受伤。现有证据不能证明另一学生存在故意或重大过失，场地合格且学校已作安全提示。",
        "dispute_focus": "学生自发参加具有一定风险的体育活动受伤，如何适用自甘风险规则以及判断学校责任。",
        "judgment_result": "审理法院判决驳回受伤学生要求另一学生及其监护人、学校共同赔偿的诉讼请求。",
        "judgment_reasoning": "足球具有对抗性，参与者自愿参加并应认知通常风险；另一参与者无明显违规动作，学校也不是活动组织者且已尽教育管理职责，均不承担本案赔偿责任。",
        "ai_plain_language": "参加足球、篮球等对抗性活动受伤，不一定能要求同学或学校赔偿。关键要看对方是否故意或有重大过失、谁组织活动、场地是否安全以及学校是否尽到提醒管理义务。",
        "keywords": "学生,校园体育,自甘风险,健康权,学校责任",
        "source_external_id": "spc-463111-case-4",
        "source_url": SOURCE_URL,
        "categories": ("campus-rights",),
        "tags": ("学生事实明确", "校园体育", "自甘风险"),
        "laws": (("中华人民共和国民法典", "第一千一百七十六条、第一千二百条", "自甘风险与学校教育管理责任"),),
    },
    {
        "slug": "spc-2025-campus-management-05-discipline",
        "title": "李小某诉某学校教育机构责任纠纷案",
        "case_number": "最高法2025年涉校园管理民事纠纷典型案例五",
        "guiding_case_number": "",
        "court_name": "最高人民法院发布典型案例",
        "case_type": "民事",
        "cause": "教育机构责任纠纷",
        "legal_domain": "campus",
        "decision_date": None,
        "published_at": datetime(2025, 4, 23, 15, 6, 45),
        "summary": "一年级学生在校扎、咬同学，老师与家长沟通并要求其在班会上郑重道歉。监护人认为当众道歉造成心理伤害，起诉学校索赔。",
        "dispute_focus": "教师要求违规学生赔礼道歉是否属于合理教育惩戒，学校是否因此承担侵权责任。",
        "judgment_result": "审理法院认定现有事实不足以证明学校超越或滥用教育惩戒权，判决驳回诉讼请求。",
        "judgment_reasoning": "教师针对学生扎、咬同学的行为进行批评并要求道歉，属于正常教育管理，未超出规则允许的合理教育惩戒范围。",
        "ai_plain_language": "学校可以依法采取适度教育惩戒，但不能侮辱、体罚或滥用权力。发生争议时，应保存沟通记录、校规、处理过程和对学生实际影响的材料。",
        "keywords": "学生,教育惩戒,学校管理,赔礼道歉,教育机构责任",
        "source_external_id": "spc-463111-case-5",
        "source_url": SOURCE_URL,
        "categories": ("campus-rights",),
        "tags": ("学生事实明确", "教育惩戒", "学校管理"),
        "laws": (("中华人民共和国教育法", "第二十九条", "学校对受教育者实施奖励或处分的权利"),),
    },
    {
        "slug": "spc-2025-campus-management-06-school-reputation",
        "title": "某小学诉张某某网络侵权责任纠纷案",
        "case_number": "最高法2025年涉校园管理民事纠纷典型案例六",
        "guiding_case_number": "",
        "court_name": "最高人民法院发布典型案例",
        "case_type": "民事",
        "cause": "网络侵权责任纠纷",
        "legal_domain": "campus",
        "decision_date": None,
        "published_at": datetime(2025, 4, 23, 15, 6, 45),
        "summary": "学生家长不满学校管理，在多个社交平台发布指向明确的激烈内容，所称事实经调查不属实，诉讼中也未能举证，相关内容被广泛传播。",
        "dispute_focus": "家长监督学校和表达维权诉求的边界，虚构事实并以侮辱性言辞传播是否侵害学校名誉权。",
        "judgment_result": "判决家长向学校书面赔礼道歉，并赔偿相应经济损失及合理开支。",
        "judgment_reasoning": "家长有监督和合法维权的权利，但公开表达应理性、客观、真实；在不能证明事实的情况下传播侮辱诽谤内容并导致学校社会评价降低，构成名誉权侵害。",
        "ai_plain_language": "对学校处理不满可以投诉、申诉和公开监督，但发帖前要保存证据、区分事实与评价，避免使用无法证明的指控和侮辱性措辞。",
        "keywords": "学生家长,学校管理,网络发帖,名誉权,合理监督",
        "source_external_id": "spc-463111-case-6",
        "source_url": SOURCE_URL,
        "categories": ("campus-rights",),
        "tags": ("学生事实明确", "家校纠纷", "网络名誉权"),
        "laws": (("中华人民共和国民法典", "第一千零二十四条", "名誉权及禁止侮辱、诽谤"),),
    },
)


STUDENT_CASE_SLUGS = frozenset({
    "guiding-case-38-tian-yong-v-ustb",
    "guiding-case-39-he-xiaoqiang-v-hust",
    "guiding-case-14",
    "guiding-case-225",
    "guiding-case-227",
    *(item["slug"] for item in RECENT_STUDENT_CASES),
})
